### ISSUE TITLE
Create Proxy Level

### ISSUE THREAD

**Issue by zhixson** [farmersanonymous/killer-bunnies#2]
(Sort of a test ticket and probably created poorly)
Create a correctly sized proxy level fbx to get the ball rolling. 
Should contain proxy versions of most models in their expected locations.

- Ground plane
- Fence
- Trees/Shrubs
- Shed
- Gate
- Carrot Crops
- Burrows
- Meteor
- Wheelbarrow
- Harvest Basket (Place to deposit carrots)

Note: The gate, shed, meteor, and wheelbarrow are models meant as scenery for each of the four quadrants of the map to make them interesting.

Try to use instanced geometry where possible and deliver as a .gltf file

**Comment by albinochicken** [comment]
Blockout currently includes:
* Ground
* Meteorite
* Shed
* Well
* Fencing
* Tilled Rows
* Trees
* Harvest Basket (will be replace with vegetable cart most likely)

Missing:
* Gate
* Shrubs

Separated Out:
* Burrow
* Carrot
