### ISSUE TITLE
Radar

### ISSUE THREAD

**Issue by ericbroberic** [farmersanonymous/killer-bunnies#24]
Radar system that can show off the whole map in the corner. Outline of player/enemies can be colored dots on the screen.

EDIT:
Minimap for corner of screen that displays information to the player about where the enemies are in relation to the play area and the farmer.

BASE REQUIREMENTS:
- Minimap size and aspect ratio will mirror that of the gameplay (fenced in) area (whole play area always represented, not just a perimeter around the player)
- Minimap will use a separate orthographic camera to overlay the gameplay camera
- Player represented by a yellow dot (slightly bigger than enemy dots)
- Stabber bunnies represented by red dots
- Nabber bunnies represented by orange dots
- Minimap will be aligned with the screen's rectangle, not the camera angle (which is going to be roughly 30-45 degrees angled)
- The dots will only represent positions of the players, not any other information

SIMPLIFIED DESIGN (based on 1920x1080 resolution)
- Dark grey background at approximately 15-25% opacity
- Background stroked on the edges with light grey of 2-4 pixels, at approximately 25-50% opacity
- Farmer Dot: Approximately 16 pixels in size
- Enemy Dot: Approximately 8 pixels in size

- Dots possibly full opacity, but if they feel like they are in the way, then as low as 50% opacity

NICE TO HAVE:
- Possibly have a VERY faded version of the play area, top down orthographic camera as a background instead of standard grey
- OR Possibly have standard grey, but with artistic landmarks in the corners of the minimap (meteorite, well, shed, gate) to help represent the play area

NOTES:
- Colors of the dots subject to change
- See attached image for basic idea
- Due to virtual thumbsticks for mobile, I'm guessing it will be best to place the minimap in one of the upper corners of the screen.  That said, if possible, maybe we can keep it in a lower corner by default, but then move it to either upper corner or even bottom-middle when using virtual sticks.  Certainly this may need playtesting if we do it.

![MinimapExample](https://user-images.githubusercontent.com/55606530/82277473-ed41be00-9955-11ea-84cb-f402e4de2bde.png)

**Comment by SweetAlmighty** [comment]
@ericbroberic Are we talking an actual radar, or just some sort of simplified minimap? I've been messing around with the latter (with a separate camera and such), but the former might be way easier to implement.

**Comment by ericbroberic** [comment]
@albinochicken has stronger opinions on it, so hopefully he can interject, but I think just a radar with a wider range then the main camera could work.

**Comment by albinochicken** [comment]
@SweetAlmighty @ericbroberic So what I intended was a minimap when I brought it up.  Didn't think about the terminology enough when mentioning.  So I understand if there are difficulties.  I'll lay out the intention here and then y'all can decide if it's easier when it's more clear, or if it still will be difficult to implement.  I'll edit the description of the ticket and upload a screenshot/concept.

**Comment by albinochicken** [comment]
@SweetAlmighty  @ericbroberic ok it's updated.  Let me know if you have questions or concerns, or if we need to edit anything go for it.

**Comment by albinochicken** [comment]
@SweetAlmighty  @ericbroberic  So I know this is in an open state still... but when I was looking for something in a build I came across the radar build.  Noticed that the radar is squashing based on the canvas size as opposed to the play area.  As a result, the dots are also squashing.  I realize this may be known, but just wanted to drop a note here just in case.

**Comment by SweetAlmighty** [comment]
@albinochicken It's drawn to a static viewport, if the size of the canvas changes, it will change. With just over a week left, I'll leave it to everyone else whether this needs to be "fixed".

**Comment by albinochicken** [comment]
@SweetAlmighty that's fine.  I have no idea what is priority on the dev side right now.  Just wanted to mention it and y'all can figure out if it should be fixed.  I just noticed it so figured I'd mention.  Technically I would have filed a bug ticket had this not been open still, and let that get prioritized.  I'm well aware of the time.  lol  pulling my own hair out too.
