### ISSUE TITLE
Create Garden Fencing

### ISSUE THREAD

**Issue by zhixson** [farmersanonymous/killer-bunnies#25]
Create a re-usable section of garden fence that cleanly fits along the border of the garden. 

- Stylized
- Wood
- Weathered
- PBR Material (BaseColor, AO, Roughness, Metalness, Normal)

If no concept attached, feel free to seek one out.

**Comment by albinochicken** [comment]
![Reference_Wood](https://user-images.githubusercontent.com/55606530/81489346-4a48c000-9242-11ea-91f2-b8bd082ab443.PNG)
reference for wood style

**Comment by albinochicken** [comment]
Blockout was created and included with environment
