### ISSUE TITLE
Create Garden Carrot Model

### ISSUE THREAD

**Issue by zhixson** [farmersanonymous/killer-bunnies#30]
Create a small carrot model for harvesting animations.
- Stylized
- Small
- Needs to be recognizable as a carrot when stuck in the ground
- Potentially need some blendshape animation to show growth or playfully animate when being harvested
- PBR Material (BaseColor, AO, Roughness, Metalness, Normal)

**Comment by albinochicken** [comment]
Blockout created and uploaded
