### ISSUE TITLE
Create Rabbit Spawning Burrow

### ISSUE THREAD

**Issue by zhixson** [farmersanonymous/killer-bunnies#31]
Create a model of a rabbit burrow that features a hole surrounded by raised dirt.
Stylized

- Same color as the ground plane dirt texture
- Hole and dirt ring large enough to be easily readable
- Placed on top of ground, hole does not intersect ground.
- PBR Material (BaseColor, AO, Roughness, Metalness, Normal)

**Comment by albinochicken** [comment]
Blockout created and uploaded
