### ISSUE TITLE
Create Bruiser Carrot Model

### ISSUE THREAD

**Issue by zhixson** [farmersanonymous/killer-bunnies#41]
Create the model for the Bruiser Carrot enemy

- A-Pose
- PBR Material (BaseColor, AO, Roughness, Metalness, Normal)

![BruiserCarrotConcept01](https://user-images.githubusercontent.com/64786619/81028901-299ef580-8e51-11ea-8363-79c68a8dc87f.png)

**Comment by ericbroberic** [comment]
No longer doing the bruiser carrot.
