### ISSUE TITLE
Adjust Dampening of Camera

### ISSUE THREAD

**Issue by albinochicken** [farmersanonymous/killer-bunnies#74]
Currently the player speed can go faster than the camera, so the player can actually get off-screen relatively easily.

Use image as guide for the following:
* Camera would shift in a way that the player is never outside of the imaginary drawn (in red) box
* This inner box would be proportional with the screen ratio
* When the player is idle (or stops moving), the camera would softly transition so that the player is centered in the camera visually
* As the player moves, the camera would softly (dampen) transition
* As the player approaches the edge of this inner box, the camera would softly shift to catch up to the player and offset such that the camera is allowing the player maximum view distance in the direction the player is moving
** Example1: If the player is running to the right, the camera would have the player slightly off-center where the player is visually at the left side of the inner box, to have more viewable area in front of the player
** Example2: If the player is moving down-right, and abruptly starts moving in the opposite direction, up-left, then the camera would softly transition so that visibly the player has gone from upper-left of the inner box to lower-right of the inner box, always maintaining the most viewable area in front of the player (i.e. in the direction the player is moving).

PLEASE NOTE: This was observed with the static proxy player model, so it's possible things will be improved upon once the animated version is in place.

![CameraDampening](https://user-images.githubusercontent.com/55606530/81626801-bc4c1100-93ca-11ea-8a7b-ba2fd5907442.PNG)

**Comment by ericbroberic** [comment]
Camera is "good enough".
